In [1]:
import pandas as pd
import numpy as np
import os

In [16]:
big_df = pd.DataFrame()
for filename in os.listdir(os.getcwd()):
    if 'csv' in filename:
        with open(os.path.join(os.getcwd(), filename), 'r') as f:
            temp_df = pd.read_csv(filename).iloc[:25, :] # Remove max, min, median
            temp_df['State'] = filename[17:-4] # Add state's name
            big_df = pd.concat([big_df, temp_df])

In [17]:
big_df

,Unnamed: 0,Janeiro,Fevereiro,Março,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro,Total,State
0,1998,-,-,-,-,-,3,35,131,512,44,-,7,732,acre
1,1999,-,-,-,-,-,-,1,67,212,63,4,-,347,acre
2,2000,-,-,11,1,1,1,1,136,261,18,-,-,430,acre
3,2001,-,-,-,-,-,1,3,399,288,137,1,-,829,acre
4,2002,-,1,-,-,-,-,59,1268,4337,932,139,3,6739,acre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,2018,97,16,64,127,599,914,1321,1361,1796,1371,201,166,8033,tocantins
21,2019,84,78,82,209,690,1406,1598,2916,4505,1462,376,219,13625,tocantins
22,2020,75,77,111,221,446,1188,1361,1714,3977,2192,520,211,12093,tocantins
23,2021,76,56,65,85,851,1149,1794,2757,1785,1213,131,45,10007,tocantins
24,2022,57,62,49,134,1103,1370,1710,2298,2753,2327,143,-,12006,tocantins

In [18]:
big_df.to_csv('n_fires_per_state_1998_2022.csv')